image: node:10.16.0

test:
  stage: test
  before_script: 
    - npm install 
  script:
    - npm run test

pages:
  stage: deploy
  before_script: 
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - public
  only:
    - master